version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./:/app/database
    working_dir: /app
    command: python3 -m database.app

  db:
    image: postgres:latest
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
